### ISSUE TITLE
lein template doesn't work

### ISSUE THREAD

**Issue by w1kee** [discljord/discljord#129]
**Describe the bug**
when using the lein template, there's a macroexpanding syntax error

**Version Information**
 - Clojure Version: 1.11.1.1386
 - Discljord Version: N/A
 - OS bot is hosted on: N/A
 - Leiningen Version: 2.10.0

**To Reproduce**
1. run lein new discljord discord-clojure

Minimal reproduction case:
Add a github link to a repo which includes a minimal reproduction case (if possible).
N/A

**Expected behavior**
the project should be generated without error

**Logs**
$ lein new discljord discord-clojure
Retrieving discljord/lein-template/0.2.1/lein-template-0.2.1.pom from clojars
Retrieving java-http-clj/java-http-clj/0.4.3/java-http-clj-0.4.3.pom from clojars
Retrieving discljord/lein-template/0.2.1/lein-template-0.2.1.jar from clojars
Retrieving java-http-clj/java-http-clj/0.4.3/java-http-clj-0.4.3.jar from clojars
Could not load template, failed with: Syntax error macroexpanding at (java_http_clj/core.clj:1:1).

**Additional context**
i apologise if this is a simple problem that i could've fixed, i'm new to clojure.

**Comment by JohnnyJayJay** [comment]
Thanks for the report, I will take a look.

For the future, report issues with the leiningen template [here](https://github.com/discljord/lein-discljord-template)

**Comment by JohnnyJayJay** [comment]
What Java Version do you have installed @w1kee ? You can check by running `java -version`. It has to be at least version 11.

**Comment by w1kee** [comment]
ok, i was on java 8, i've switched to java 17 and now it works, thank you very much for help
