### ISSUE TITLE
Reflection warning in discljord.util ns

### ISSUE THREAD

**Issue by pmonks** [discljord/discljord#96]
**Describe the bug**
I use [`clj-check`](https://github.com/athos/clj-check) to compile my code and discover reflection warnings, and that tool happens to recursively compile and report reflection warnings for everything that my code transitively depends on. [Normally this is a problem](https://github.com/athos/clj-check/issues/4), but in this case it works to our advantage... but I digress...

In running this tool against my Discord bots (for example, [`for-science`](https://github.com/pmonks/for-science)), I get this reflection warning from the `discljord.util` ns:
```
Reflection warning, discljord/util.clj:63:56 - call to static method isDigit on java.lang.Character can't be resolved (argument types: unknown).
```

**Version Information**
 - Clojure Version: 1.10.3
 - Discljord Version: 1.3.0
 - OS bot is hosted on: Linux

**To Reproduce**
1. Check out [`for-science`](https://github.com/pmonks/for-science)
2. Run `clj -T:build check` in the checked out directory (this command runs `clj-check`)

Minimal reproduction case:
[https://github.com/pmonks/for-science](https://github.com/pmonks/for-science)

**Expected behavior**
There are no reflection warnings reported by `clj-check`, for any discljord namespaces.

**Logs**
n/a

**Additional context**
n/a

**Comment by IGJoshua** [comment]
Fixed on develop, thanks for the report!
